backend:
  name: github
  repo: aquilapartments/website
  branch: master
  base_url: http://aquilataormina.com:3000
media_folder: "public/uploads"
collections:
  - name: "homeslider"
    label: "Slider home"
    folder: "src/contents/homeslider"
    create: true
    slug: "{{type}}-{{order}}"
    fields:
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption IT", name: "caption_it", widget: "string", required: false}
      - {label: "Caption EN", name: "caption_en", widget: "string", required: false}
      - {label: "Caption DE", name: "caption_de", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "select", options: ["top", "bottom"]}
  - name: "homebox"
    label: "Box home"
    folder: "src/contents/homebox"
    create: true
    slug: "{{order}}"
    fields:
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Title EN", name: "title_en", widget: "string"}
      - {label: "Text EN", name: "text_en", widget: "string"}
      - {label: "Title IT", name: "title_it", widget: "string"}
      - {label: "Text IT", name: "text_it", widget: "string"}
      - {label: "Title DE", name: "title_de", widget: "string"}
      - {label: "Text DE", name: "text_de", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
  - name: "extra"
    label: "Extra Service Home"
    folder: "src/contents/extraservice"
    create: true
    slug: "{{order}}"
    fields:
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Title IT", name: "title_it", widget: "string"}
      - {label: "Title EN", name: "title_en", widget: "string"}
      - {label: "Title DE", name: "title_de", widget: "string"}
      - {label: "Description IT", name: "description_it", widget: "string", required: false}
      - {label: "Description EN", name: "description_en", widget: "string", required: false}
      - {label: "Description DE", name: "description_de", widget: "string", required: false}
  - name: "translations"
    label: "Translations"
    folder: "src/contents/translations"
    create: true
    slug: "{{global}}"
    fields:
      - {label: "Global", name: "global", widget: "string"}
      - {label: "English", name: "en", widget: "string"}
      - {label: "Italian", name: "it", widget: "string"}
      - {label: "German", name: "de", widget: "string"}
  - name: "accomodation"
    label: "Accomodation"
    folder: "src/contents/accomodation"
    create: true
    slug: "{{title}}-{{language}}"
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["it","en","de"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Initial Description", name: "init_description", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Map", name: "location", widget: "string" }
      - {label: "Long description", name: "long_description", widget: "markdown"}
      - {label: "Right title 1", name: "right_title_1", widget: "string"}
      - {label: "Right description 1", name: "right_description_1", widget: "markdown"}
      - {label: "Right title 2", name: "right_title_2", widget: "string"}
      - {label: "Right description 2", name: "right_description_2", widget: "markdown"}
      - {label: "Right title 3", name: "right_title_3", widget: "string"}
      - {label: "Right description 3", name: "right_description_3", widget: "markdown"}
      - {label: "Right title 4", name: "right_title_4", widget: "string"}
      - {label: "Right description 4", name: "right_description_4", widget: "markdown"}
      - {label: "Main image", name: "main_image", widget: "image"}
  - name: "accomodationslider"
    label: "Slider accomodation"
    folder: "src/contents/accomodationslider"
    create: true
    slug: "{{order}}"
    fields:
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "about"
    label: "About Taormina"
    folder: "src/contents/about"
    create: true
    slug: "{{language}}"
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["it","en","de"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "main_description", name: "main_description", widget: "markdown"}
      - {label: "secondary_description", name: "secondary_description", widget: "markdown"}
      - {label: "Main image", name: "main_image", widget: "image"}
      - {label: "Second image", name: "second_image", widget: "image"}
      - {label: "Third image", name: "third_image", widget: "image"}